//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSApp.CMSResources.XTM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XtmConnector {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XtmConnector() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMSApp.CMSResources.XTM.XtmConnector", typeof(XtmConnector).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Client cannot be empty&quot;.
        /// </summary>
        internal static string ClientRule {
            get {
                return ResourceManager.GetString("ClientRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Endpoint address cannot be reached. Please check webservice address field or contact XTM support.&quot;.
        /// </summary>
        internal static string EndpointCannotBeReached {
            get {
                return ResourceManager.GetString("EndpointCannotBeReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid webservice endpoint format&quot;.
        /// </summary>
        internal static string EndPointRule {
            get {
                return ResourceManager.GetString("EndPointRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;XtmConnect - ProjectExists: {0} or findProjectResponse.projects is null. Project IntegrationID: {1}, Project Id {2}&quot;.
        /// </summary>
        internal static string findProjectResponseIsNull {
            get {
                return ResourceManager.GetString("findProjectResponseIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Password cannot be empty&quot;.
        /// </summary>
        internal static string PasswordRule {
            get {
                return ResourceManager.GetString("PasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;XtmConnect - ProjectExists: {0} is null&quot;.
        /// </summary>
        internal static string ProjectExists {
            get {
                return ResourceManager.GetString("ProjectExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;UserName cannot be empty&quot;.
        /// </summary>
        internal static string UserNameRule {
            get {
                return ResourceManager.GetString("UserNameRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;WebserviceURI cannot be empty&quot;.
        /// </summary>
        internal static string WebserviceRule {
            get {
                return ResourceManager.GetString("WebserviceRule", resourceCulture);
            }
        }
    }
}
