//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSApp.CMSResources.XTM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XtmConnect {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XtmConnect() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMSApp.CMSResources.XTM.XtmConnect", typeof(XtmConnect).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;added&quot;.
        /// </summary>
        internal static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Add XTM translation provider&quot;.
        /// </summary>
        internal static string AddProvider {
            get {
                return ResourceManager.GetString("AddProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Connection error: &quot;.
        /// </summary>
        internal static string ConnectionError {
            get {
                return ResourceManager.GetString("ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The connection test was successful.&quot;.
        /// </summary>
        internal static string ConnectionSuccessful {
            get {
                return ResourceManager.GetString("ConnectionSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Previously saved customer does not exist in XTM system! (Customer: {0})&quot;.
        /// </summary>
        internal static string CustomerDoesNotExists {
            get {
                return ResourceManager.GetString("CustomerDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Customers and corresponding templates obtained from XTM system.&quot;.
        /// </summary>
        internal static string CustomersAndTemplates {
            get {
                return ResourceManager.GetString("CustomersAndTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Customers obtained from XTM system.&quot;.
        /// </summary>
        internal static string CustomersObtained {
            get {
                return ResourceManager.GetString("CustomersObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;DCT(s,x){}-Starting {0}. Submission id: {1}&quot;.
        /// </summary>
        internal static string DCTSubmissionStart {
            get {
                return ResourceManager.GetString("DCTSubmissionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Provider deletion error: &quot;.
        /// </summary>
        internal static string DeletionError {
            get {
                return ResourceManager.GetString("DeletionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;An error occured while cancelling translation submission. Please see exception log for more details or contact your administrator.&quot;.
        /// </summary>
        internal static string ErrorCancellingTranslation {
            get {
                return ResourceManager.GetString("ErrorCancellingTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error occured while getting customers from XTM: &quot;.
        /// </summary>
        internal static string ErrorGettingCustomers {
            get {
                return ResourceManager.GetString("ErrorGettingCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Error occured while getting templates from XTM: &quot;.
        /// </summary>
        internal static string ErrorGettingTemplates {
            get {
                return ResourceManager.GetString("ErrorGettingTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;An error occured while resubmitting translations to XTM. &quot;.
        /// </summary>
        internal static string ErrorResubmiting {
            get {
                return ResourceManager.GetString("ErrorResubmiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0} error(s) occured while checking project and jobs completion. Please see exception log for more details or contact your administrator.&quot;.
        /// </summary>
        internal static string ErrorsOccured {
            get {
                return ResourceManager.GetString("ErrorsOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;An error occured while submitting translations to XTM. &quot;.
        /// </summary>
        internal static string ErrorSubmiting {
            get {
                return ResourceManager.GetString("ErrorSubmiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;An error occured while verifying source language [{0}] support. Please see exception log for more details or contact your administrator.&quot;.
        /// </summary>
        internal static string ErrorVerifying {
            get {
                return ResourceManager.GetString("ErrorVerifying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;No customers found for given XTM account&quot;.
        /// </summary>
        internal static string NoCustomersFound {
            get {
                return ResourceManager.GetString("NoCustomersFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;You are not allowed to perform this action&quot;.
        /// </summary>
        internal static string NotAllowed {
            get {
                return ResourceManager.GetString("NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Please see exception log for more details or contact your administrator.&quot;.
        /// </summary>
        internal static string PleaseSeeExceptionLog {
            get {
                return ResourceManager.GetString("PleaseSeeExceptionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Please choose different name.&quot;.
        /// </summary>
        internal static string ProviderDiffrentName {
            get {
                return ResourceManager.GetString("ProviderDiffrentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Provider name might contain only letters and digits&quot;.
        /// </summary>
        internal static string ProviderNameRule {
            get {
                return ResourceManager.GetString("ProviderNameRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Provider with such name already exists. Please choose different name.&quot;.
        /// </summary>
        internal static string ProviderNameTaken {
            get {
                return ResourceManager.GetString("ProviderNameTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Please select customer.&quot;.
        /// </summary>
        internal static string SelectCustomer {
            get {
                return ResourceManager.GetString("SelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;--please select import type--&quot;.
        /// </summary>
        internal static string SelectImportType {
            get {
                return ResourceManager.GetString("SelectImportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Successfully deleted provider: {0}&quot;.
        /// </summary>
        internal static string SuccesfullDeleted {
            get {
                return ResourceManager.GetString("SuccesfullDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Succesfully {} Xtm translation provider: &quot;.
        /// </summary>
        internal static string SuccesfullyAction {
            get {
                return ResourceManager.GetString("SuccesfullyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Previously saved template does not exist in XTM system! (Template: {0})&quot;.
        /// </summary>
        internal static string TemplateDoesNotExists {
            get {
                return ResourceManager.GetString("TemplateDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Templates obtained from XTM system.&quot;.
        /// </summary>
        internal static string TemplatesObtained {
            get {
                return ResourceManager.GetString("TemplatesObtained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Unknown exception error. Please see exception log for more details.&quot;.
        /// </summary>
        internal static string UnknownExceptionError {
            get {
                return ResourceManager.GetString("UnknownExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;updated&quot;.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
    }
}
